Traceback (most recent call last):
  File "py/in_python_code.py", line 22, in <module>
    f1(5, 6, 7, 8)
TypeError: f1() takes 0 positional arguments but 4 were given
